version: '3.7'

services:
  database:
    image: mongo
    volumes:
      - dbdata:/data/db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    image: posterizer-api
    container_name: posterizer-api
    env_file:
      - .env
    environment:
      - DBPORT=$DBPORT
      - DBNAME=$DBNAME
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    command: npm run dev
volumes:
  node_modules:
  dbdata:
networks:
  default:
    external:
      name: localdev
