version: '3'
services:
  database:
    image: mongo
    volumes:
      - dbdata:/data/db
  nginx:
    depends_on:
      - api
      - web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  web:
    image: zavanton/posterizer-web
    build:
      context: ./web
      dockerfile: Dockerfile
  api:
    image: zavanton/posterizer-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
volumes:
  dbdata:
networks:
  default:
    external:
      name: localdev
