version: '3'
services:
  database:
    image: mongo
    volumes:
      - dbdata:/data/db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: posterizer-api
    container_name: posterizer-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - database
    command: ./wait-for.sh database:27017 -- /usr/src/app/node_modules/.bin/nodemon app.js
volumes:
  node_modules:
  dbdata:
networks:
  default:
    external:
      name: localdev
