version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: posterizer-api
    container_name: posterizer-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
networks:
  default:
    external:
      name: localdev
