apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: zavanton/posterizer-api
          ports:
            - containerPort: 5000
          env:
            - name: DBNAME
              value: 'posterizer'
            - name: PGHOST
              value: mongo-cluster-ip-service
            - name: DBPORT
              value: '27017'
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: appsecret
                  key: APPSECRET