apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: zavanton/posterizer-api
          ports:
            - containerPort: 5000
          env:
            - name: DBHOST
              value: mongo-cluster-ip-service
            - name: DBPORT
              value: '27017'
            - name: DBNAME
              value: posterizer
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: appsecret
                  key: APPSECRET
